import httpx

base = 'http://localhost:8000/api/v1'
r = httpx.post(f'{base}/auth/login', params={'email': 'admin@demo.example.com', 'password': 'admin123'})
token = r.json()['access_token']
headers = {'Authorization': f'Bearer {token}'}

jobs = [
    {"title": "Staff Engineer", "description": "Lead technical architecture and drive engineering excellence across multiple teams. You will define technical strategy, mentor senior engineers, and solve the hardest problems at scale. Must have experience with distributed systems.", "skills": ["Python", "Go", "Kubernetes", "System Design", "AWS", "Microservices"], "experience_min": 8, "experience_max": 15, "education": "Master's", "location": "Seattle, USA", "remote_allowed": True, "salary_min": 200000, "salary_max": 320000},
    {"title": "iOS Developer", "description": "Build beautiful native iOS applications using Swift and SwiftUI. You will work on our consumer-facing mobile app used by millions. Experience with Core Data, Combine, and App Store deployment required.", "skills": ["Swift", "SwiftUI", "iOS", "Xcode", "Core Data", "REST APIs"], "experience_min": 3, "experience_max": 6, "education": "Bachelor's", "location": "Austin, USA", "remote_allowed": True, "salary_min": 120000, "salary_max": 170000},
    {"title": "Data Engineer", "description": "Build and maintain data pipelines that process terabytes of data daily. You will design data warehouse schemas, build ETL pipelines, optimize query performance, and ensure data quality across the organization.", "skills": ["Python", "Spark", "Airflow", "SQL", "Snowflake", "dbt", "AWS"], "experience_min": 3, "experience_max": 7, "education": "Bachelor's in CS", "location": "Chicago, USA", "remote_allowed": True, "salary_min": 130000, "salary_max": 185000},
    {"title": "Technical Writer", "description": "Create clear and comprehensive technical documentation for our developer platform. You will write API docs, tutorials, guides, and maintain our developer portal. Strong writing skills and technical background required.", "skills": ["Technical Writing", "API Documentation", "Markdown", "Git", "REST APIs"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Remote, USA", "remote_allowed": True, "salary_min": 80000, "salary_max": 120000},
    {"title": "Engineering Manager", "description": "Lead a team of 8-10 engineers building our core platform. You will drive execution, remove blockers, grow your team members careers, and collaborate with product and design to deliver impactful features on time.", "skills": ["Leadership", "Agile", "Python", "System Design", "Hiring", "Mentoring"], "experience_min": 6, "experience_max": 12, "education": "Bachelor's in CS", "location": "Boston, USA", "remote_allowed": False, "salary_min": 180000, "salary_max": 260000},
    {"title": "Blockchain Developer", "description": "Build decentralized applications and smart contracts on Ethereum and Solana. You will design token economics, implement DeFi protocols, audit smart contracts for security, and integrate with Web3 wallets.", "skills": ["Solidity", "Ethereum", "Web3.js", "Rust", "Smart Contracts", "DeFi"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Zurich, Switzerland", "remote_allowed": True, "salary_min": 100000, "salary_max": 160000},
    {"title": "Site Reliability Engineer", "description": "Ensure 99.99% uptime for our global platform serving 50M users. You will build monitoring dashboards, automate incident response, optimize infrastructure costs, and drive reliability improvements across all services.", "skills": ["Linux", "Kubernetes", "Prometheus", "Grafana", "Terraform", "Python", "AWS"], "experience_min": 4, "experience_max": 8, "education": "Bachelor's in CS", "location": "Dublin, Ireland", "remote_allowed": True, "salary_min": 85000, "salary_max": 130000},
    {"title": "Embedded Systems Engineer", "description": "Design firmware for our IoT devices deployed in smart homes worldwide. You will write C/C++ code for ARM microcontrollers, implement wireless protocols, optimize power consumption, and debug hardware interfaces.", "skills": ["C", "C++", "ARM", "RTOS", "IoT", "Embedded Linux", "BLE"], "experience_min": 3, "experience_max": 7, "education": "Bachelor's in EE", "location": "Munich, Germany", "remote_allowed": False, "salary_min": 65000, "salary_max": 95000},
    {"title": "Scrum Master", "description": "Facilitate agile ceremonies and drive continuous improvement across three development teams. You will coach teams on Scrum practices, remove impediments, track velocity metrics, and foster a culture of collaboration.", "skills": ["Scrum", "Agile", "Jira", "Confluence", "Facilitation", "Coaching"], "experience_min": 3, "experience_max": 6, "education": "Bachelor's", "location": "Barcelona, Spain", "remote_allowed": True, "salary_min": 50000, "salary_max": 75000},
    {"title": "Salesforce Developer", "description": "Customize and extend our Salesforce CRM platform. You will build custom Lightning components, write Apex triggers, design complex workflows, integrate with external systems, and manage deployments.", "skills": ["Salesforce", "Apex", "Lightning", "SOQL", "JavaScript", "REST APIs"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Paris, France", "remote_allowed": True, "salary_min": 55000, "salary_max": 85000},
    {"title": "Game Developer", "description": "Create engaging mobile games using Unity engine. You will implement game mechanics, optimize rendering performance, integrate analytics and monetization SDKs, and collaborate with artists and game designers.", "skills": ["Unity", "C#", "Game Design", "3D Math", "Shaders", "Mobile"], "experience_min": 2, "experience_max": 6, "education": "Bachelor's", "location": "Seoul, South Korea", "remote_allowed": False, "salary_min": 50000000, "salary_max": 80000000},
    {"title": "Solutions Architect", "description": "Design end-to-end technical solutions for enterprise clients. You will lead discovery workshops, create architecture diagrams, write technical proposals, and guide implementation teams through complex integrations.", "skills": ["AWS", "Azure", "Solution Design", "Microservices", "Enterprise", "Pre-sales"], "experience_min": 6, "experience_max": 12, "education": "Bachelor's in CS", "location": "Melbourne, Australia", "remote_allowed": True, "salary_min": 140000, "salary_max": 200000},
    {"title": "React Native Developer", "description": "Build cross-platform mobile applications for our fintech product used across Southeast Asia. You will implement payment flows, biometric auth, push notifications, and offline-first architecture.", "skills": ["React Native", "TypeScript", "Redux", "Firebase", "iOS", "Android"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Jakarta, Indonesia", "remote_allowed": True, "salary_min": 15000000, "salary_max": 30000000},
    {"title": "Machine Learning Engineer", "description": "Deploy ML models to production at scale. You will build feature stores, implement model serving infrastructure, set up A/B testing frameworks, and optimize inference latency for real-time predictions.", "skills": ["Python", "TensorFlow", "Kubernetes", "MLflow", "FastAPI", "Docker"], "experience_min": 3, "experience_max": 7, "education": "Master's", "location": "Hyderabad, India", "remote_allowed": False, "salary_min": 2000000, "salary_max": 3500000},
    {"title": "PHP Laravel Developer", "description": "Develop and maintain our e-commerce platform built on Laravel. You will implement new features, write unit tests, optimize database queries, integrate payment gateways, and handle high-traffic loads.", "skills": ["PHP", "Laravel", "MySQL", "Redis", "Vue.js", "REST APIs"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Manila, Philippines", "remote_allowed": True, "salary_min": 800000, "salary_max": 1500000},
    {"title": "SAP Consultant", "description": "Implement and customize SAP S/4HANA for enterprise clients. You will gather requirements, configure modules, manage data migration, and provide post-go-live support for complex ERP implementations.", "skills": ["SAP", "S/4HANA", "ABAP", "FICO", "Project Management", "ERP"], "experience_min": 5, "experience_max": 10, "education": "Bachelor's", "location": "Riyadh, Saudi Arabia", "remote_allowed": False, "salary_min": 30000, "salary_max": 50000},
    {"title": "Network Engineer", "description": "Design and maintain enterprise network infrastructure including firewalls, VPNs, load balancers, and SD-WAN. You will troubleshoot connectivity issues and ensure network security compliance.", "skills": ["Cisco", "Networking", "Firewall", "SD-WAN", "BGP", "Linux", "Security"], "experience_min": 3, "experience_max": 7, "education": "Bachelor's in CS", "location": "Lagos, Nigeria", "remote_allowed": False, "salary_min": 5000000, "salary_max": 10000000},
    {"title": "Digital Marketing Manager", "description": "Lead our digital marketing strategy across SEO, SEM, social media, and email campaigns. Manage marketing budget, optimize conversion funnels, and drive user acquisition growth.", "skills": ["SEO", "Google Ads", "Analytics", "Social Media", "Content Strategy", "A/B Testing"], "experience_min": 4, "experience_max": 8, "education": "Bachelor's", "location": "Cape Town, South Africa", "remote_allowed": True, "salary_min": 600000, "salary_max": 1000000},
    {"title": "Technical Support Engineer", "description": "Provide expert technical support for our cloud platform customers. Troubleshoot complex issues, write knowledge base articles, and maintain high customer satisfaction scores.", "skills": ["Linux", "AWS", "Networking", "SQL", "Troubleshooting", "Communication"], "experience_min": 1, "experience_max": 4, "education": "Bachelor's", "location": "Nairobi, Kenya", "remote_allowed": True, "salary_min": 1500000, "salary_max": 3000000},
    {"title": "Ruby on Rails Developer", "description": "Build and scale our marketplace platform using Ruby on Rails. Develop RESTful APIs, implement background jobs with Sidekiq, optimize PostgreSQL queries, and deploy using AWS.", "skills": ["Ruby", "Rails", "PostgreSQL", "Redis", "Sidekiq", "JavaScript", "Docker"], "experience_min": 2, "experience_max": 6, "education": "Bachelor's", "location": "Buenos Aires, Argentina", "remote_allowed": True, "salary_min": 3000000, "salary_max": 6000000},
    {"title": "Database Administrator", "description": "Manage and optimize PostgreSQL and MongoDB database clusters. Handle replication, backup strategies, performance tuning, capacity planning, and disaster recovery.", "skills": ["PostgreSQL", "MongoDB", "MySQL", "Replication", "Backup", "Linux", "Python"], "experience_min": 4, "experience_max": 8, "education": "Bachelor's in CS", "location": "Mexico City, Mexico", "remote_allowed": False, "salary_min": 40000, "salary_max": 70000},
    {"title": "Angular Developer", "description": "Build enterprise web applications using Angular and TypeScript. Implement complex UI components, state management with NgRx, write unit tests, and integrate with RESTful and GraphQL APIs.", "skills": ["Angular", "TypeScript", "RxJS", "NgRx", "HTML", "CSS", "REST APIs"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Bogota, Colombia", "remote_allowed": True, "salary_min": 8000000, "salary_max": 15000000},
    {"title": "Developer Advocate", "description": "Be the voice of our developer platform. Create tutorials, speak at conferences, build demo apps, engage with the developer community, and gather feedback to improve our APIs.", "skills": ["Public Speaking", "Technical Writing", "Python", "JavaScript", "Developer Relations", "APIs"], "experience_min": 3, "experience_max": 7, "education": "Bachelor's", "location": "Remote, Worldwide", "remote_allowed": True, "salary_min": 110000, "salary_max": 160000},
    {"title": "Rust Systems Programmer", "description": "Build high-performance systems software in Rust. Work on our database engine, implement concurrent data structures, optimize memory usage, and contribute to open-source Rust libraries.", "skills": ["Rust", "Systems Programming", "Concurrency", "Linux", "C", "Performance"], "experience_min": 3, "experience_max": 8, "education": "Bachelor's in CS", "location": "Remote, Europe", "remote_allowed": True, "salary_min": 90000, "salary_max": 150000},
    {"title": "Kubernetes Platform Engineer", "description": "Build and operate our internal developer platform on Kubernetes. Create Helm charts, implement GitOps workflows, build custom operators, and enable self-service deployments.", "skills": ["Kubernetes", "Helm", "ArgoCD", "Go", "Terraform", "Docker", "GitOps"], "experience_min": 4, "experience_max": 8, "education": "Bachelor's in CS", "location": "Remote, Asia Pacific", "remote_allowed": True, "salary_min": 100000, "salary_max": 155000},
    {"title": "Growth Hacker", "description": "Drive rapid user growth through data-driven experimentation. Design growth loops, run A/B tests, optimize onboarding funnels, implement referral programs, and analyze cohort retention.", "skills": ["Analytics", "A/B Testing", "SQL", "Python", "Product", "Marketing"], "experience_min": 2, "experience_max": 5, "education": "Bachelor's", "location": "Remote, Worldwide", "remote_allowed": True, "salary_min": 90000, "salary_max": 140000},
    {"title": "WordPress Developer", "description": "Build custom WordPress themes and plugins for agency clients. Create responsive designs, implement WooCommerce stores, optimize performance, and provide ongoing maintenance.", "skills": ["WordPress", "PHP", "JavaScript", "CSS", "WooCommerce", "MySQL"], "experience_min": 1, "experience_max": 4, "education": "Bachelor's", "location": "Warsaw, Poland", "remote_allowed": True, "salary_min": 8000, "salary_max": 15000},
]

created = 0
for job in jobs:
    r = httpx.post(f'{base}/jobs', params=job, headers=headers)
    if r.status_code == 201:
        jid = r.json()['id']
        httpx.post(f'{base}/jobs/{jid}/publish', headers=headers)
        created += 1
    else:
        print(f'SKIP: {job["title"]} (may already exist)')

print(f'{created} new jobs created')
r = httpx.get(f'{base}/portal/jobs')
print(f'Total active jobs on portal: {r.json()["total"]}')
